- name: Labeler
  uses: actions/labeler@v4.0.0


jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
[![.github/workflows/labeler.yml](https://github.com/Bryan-Roe/interna/actions/workflows/labeler.yml/badge.svg?branch=main)](https://github.com/Bryan-Roe/interna/actions/workflows/labeler.yml)
